travis:
  secure:
    BINSTAR_TOKEN: HUTPcYO93rL0v/DqisioF1hfud2s3cm/xa9zzu4INXOjCUUq4dU1TlAnVvgRCRN54N5JZw3MNdTwQuGzAfCksA3l1dOGFAJFVliAMNxYlXiVgu/ncF1y5rqvuvRE/uUyfAX60DO7T5mwi1ZLooRyjxyQyNZxfWv+4HKp5cA2e3BD7aPe83ZhLZ/iMJ8CuOKkNVhPm00uaEZAm0WPS5an4jBv9J9qD9Avwip8Yu40sRfEcRrIB/op14WsSEz07Tu7mFnFQ2S3Gg9BSqH7BIS3xguhugqEb2H/Blbp1LH+cM7xTxgYmuBAgW0dR3NDSZM01aKx4L3LvV3LTp6+cJ6asRBozzf/NQQZQsW4WsPBB8TKA/VtUe8HFK3wIRQK/bXAQkrFYnh2x98CV7QCiaMLwv7RtBwgKzVHiMC/KahHB5jDjDe3e5aLEMQEp1KWcqfbYmDos1oZSfeq0dhgvl+QiBtmXKKoIBe2+TU3D6+xPLgH6cmhwmyaGqnZJpFO0l0Zv2vV04M4LnHX4DfE/zX5RXSFTJmJOFSRp0KDp8efwS3t5HvC28oAMCE6i1v2UMgbqiI3LjvYQDpnrPNadyRoRMqrVLYEcqq9BIQlAwi5hHgdb+0T72CvOS48udesRQpF/3SUvhjxn0LrJRAA6wcnJSHVo/y+CA2CXHPR4bXyt2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
