travis:
  secure:
    BINSTAR_TOKEN: UaQp8ZtLrKxZOvqEO/6ZMYiH7xMMbOUU0vVU/VKf06UKuWS6PLFg9LNmkPHW5vQ4x8U+B8Gcx7rS+xIhdahmoKkfBJeme8BZkwGeDQgQuVao/yRKuzTlpUmS2v64Zd+QXhTD6N6z9gfQSmoO/avBVAM1+CLCL95cASyXI2jFN0Yvac92YP3HCAhzrJI3GOvLxfoqOScsBpRmXnl+7+FXq7UZf9+7IHciY/TgycUZq2DUP9VxEFMA7G4j7CLZb6oZcLeZdG6fZRMHo6s9Md1455W/R+AcBRY9aALchfvFVW30ONeKdMKk1ly5ygsGSikndEnDm2TbR/rg6JDJDK3w7HSU24QuneLD6ESoqt6G8y2yi4XYg+9dhmA32L4bl3TdcHfRZC1VwdtMQv6FVeiBwUXX5wCflQbZyyFOHziAo1aLZTHd3/QgDBos+AoYtzf11NwFj5lYQtYqCznMGjgd9N+S3Kr5o+ldXfRYf/PhSaeXwcJM1R5/SdbHUEpgsBMNtwnkLUGWxJ7nOA55/tvargWMz3ny2yAdsHNQlMaOOPDsvyaNWwhJD3Fpd5aT/Ge9psyBaiUdCEcSNDg8qjBaSuAsSCdBTVGUIF6A6y0w50Oky5gyHjq2wK0zB7ExlmgtaFwAwic5EepIJEYA3JlMmDuHyzmGxSGPDnB0wsZNa7s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
