travis:
  secure:
    BINSTAR_TOKEN: favBRj2wou7iRD1s7ovoakMSWKu5E+nRlM3ymLXQJPNHkzZY4VZJynKcSjBHINz3UWOhewTFH8oJC6hd68461dV28hQS2Ks6NPBQ0G4Xr7/lJlf4nNHbxhycbmKRCaGPEx3xbvowcvX+1V77tFLPSDSj8pd46aXqrzDJRXS9bBsh+c2Pi288jHtSbW1tXpJscuXYtTZy58jhhF/o85WtfS5AR5CHZmevTT7OU+j2ieRgF2vvImKIHsfjGXZMSda2RmsgU9XmRenI8tQnWdSz5DXY0Y0hGq7+L2tel1PYBkuPRRQjR+/y5JxyIdVikcQ9oPk30a2HF//cgdbfb5jcFMHwEGQcVJH04DHZS0jsFpYyWos9rK6muWVPRQkxPMAS1NS7q8mVqd2mua2ZqtSanayIM7YxCsLrSGPrP1qhaXgygvd7WKz+Qw3dypmZfBuqdRzXMQoEEE8lYQiyzw3q1RJZ282B7dA1QwTcc3M2/TFytnxbV5sYw9cvfrHaylbh9uhg3c9fbB5C+3uS5AxukmF62KJnGi4UR/RE8m4BoBnhkeYXCAineoS/AX0dP7hdVK2YD0jxD6GcBfRMZrjkHfP2+QuIjrMbZaLjywceczWKDnIYjCOIMfo/Pu/X/P0syy1JDiDTj02Ii0EDM7qYrJkp7op/5TDK5vyauXianPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
